import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Navbar from "@/components/navbar";
import { auth } from "@/lib/auth";
import { ToastContainer } from "react-toastify";
import { prisma } from "@/db/prisma";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const categories = await prisma.category.findMany({
    where: { places: { has: "NAVBAR" } }
  });
  
  return (
    <html lang="bg">
      <body className="bg-slate-100">
        <SessionProvider>
          <ToastContainer />
          <Navbar session={session} categories={categories} />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
